---

- name: Install Incus
  hosts: default
  become: true
  tasks:
    - name: install incus
      apt:
        package: incus

- name: Initialize Incus
  hosts: default
  become: false
  handlers:
    - name: reload udev rules
      command: udevadm control --reload-rules
      become: true
  tasks:
    - name: Disable lxdbr0 multicast snooping
      become: true
      copy:
        dest: /etc/udev/rules.d/99-disable-lxdbr0-mcast-snooping.rules
        content: SUBSYSTEM=="net", ACTION=="add", KERNEL=="lxdbr0", RUN+="/bin/sh -c 'echo 0 > /sys/class/net/lxdbr0/bridge/multicast_snooping'"
      notify: reload udev rules

    - meta: flush_handlers

    - name: Initialize Incus
      command:
        cmd: incus admin init --preseed
        stdin: "{{ lookup('file', 'incus_preseed.yaml') }}"
        creates: /var/lib/incus/networks/lxdbr0

...
